/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    "./src/**/*.{js,jsx,ts,tsx}",
  ],
  darkMode: "class", 
  theme: {
    extend: {
      colors: {
        "on-primary": "#ffffff", 
        "inverse-primary": "#41dbd4", 
        "on-primary-container": "#005a56", 
        "tertiary-fixed-dim": "#ffb963", 
        "primary-fixed-dim": "#41dbd4", 
        primary: "#006a66", 
        "on-primary-fixed": "#00201e", 
        background: "#f4fbf9", 
        "surface-dim": "#d5dbda", 
        "surface-container-highest": "#dde4e2", 
        "tertiary-container": "#ffb354", 
        "on-surface": "#161d1c", 
        "surface-variant": "#dde4e2", 
        "tertiary-fixed": "#ffddb9", 
        "surface-container": "#e8efee", 
        surface: "#f4fbf9", 
        error: "#ba1a1a", 
        "on-background": "#161d1c", 
        "on-secondary-fixed-variant": "#1b4e4c", 
        "surface-container-high": "#e3eae8", 
        "on-secondary": "#ffffff", 
        "on-tertiary-container": "#724600", 
        "surface-container-lowest": "#ffffff", 
        "secondary-fixed": "#b9ece8", 
        tertiary: "#865300", 
        "primary-container": "#3bd7d0", 
        "on-error-container": "#93000a", 
        "surface-container-low": "#eef5f3", 
        secondary: "#366663", 
        "inverse-surface": "#2b3231", 
        "inverse-on-surface": "#ebf2f1", 
        "on-tertiary-fixed-variant": "#663e00", 
        "on-secondary-container": "#3c6c69", 
        outline: "#6c7a78", 
        "primary-fixed": "#66f8f1", 
        "on-primary-fixed-variant": "#00504d", 
        "on-tertiary-fixed": "#2b1700", 
        "outline-variant": "#bbcac8", 
        "surface-bright": "#f4fbf9", 
        "surface-tint": "#006a66", 
        "on-surface-variant": "#3c4948", 
        "on-tertiary": "#ffffff", 
        "on-secondary-fixed": "#00201e", 
        "secondary-container": "#b9ece8", 
        "on-error": "#ffffff", 
        "secondary-fixed-dim": "#9ed0cc", 
        "error-container": "#ffdad6"
      }, 
      borderRadius: {
        DEFAULT: "0.25rem", 
        lg: "0.5rem", 
        xl: "0.75rem", 
        full: "9999px"
      }, 
      spacing: {
        sm: "8px", 
        md: "16px", 
        xl: "32px", 
        base: "4px", 
        "margin-desktop": "48px", 
        lg: "24px", 
        gutter: "16px", 
        xs: "4px", 
        "margin-mobile": "20px"
      }, 
      fontFamily: {
        "body-md": ["Inter"], 
        "headline-lg-mobile": ["Hanken Grotesk"], 
        "display-lg": ["Hanken Grotesk"], 
        "headline-sm": ["Hanken Grotesk"], 
        "body-lg": ["Inter"], 
        "label-caps": ["JetBrains Mono"], 
        "headline-md": ["Hanken Grotesk"], 
        headline: ["Hanken Grotesk"], 
        display: ["Hanken Grotesk"], 
        body: ["Inter"], 
        label: ["Jetbrains Mono"]
      }, 
      fontSize: {
        "body-md": ["14px", {lineHeight: "20px", fontWeight: "400"}], 
        "headline-lg-mobile": ["28px", {lineHeight: "36px", fontWeight: "700"}], 
        "display-lg": ["32px", {lineHeight: "40px", letterSpacing: "-0.02em", fontWeight: "700"}], 
        "headline-sm": ["20px", {lineHeight: "28px", fontWeight: "600"}], 
        "body-lg": ["16px", {lineHeight: "24px", fontWeight: "400"}], 
        "label-caps": ["12px", {lineHeight: "16px", letterSpacing: "0.05em", fontWeight: "500"}], 
        "headline-md": ["24px", {lineHeight: "32px", letterSpacing: "-0.01em", fontWeight: "600"}]
      }
    }
  },
  plugins: [],
}
